"""Content-addressed cache of every model response this project has ever seen.

This is the single most important engineering decision in the LLM layer, for a
reason that is about the thesis rather than about performance: **LLM calls are
not reproducible.** Re-running the same prompt against the same model on a
different day can return different text, and on ``claude-opus-5`` temperature
is not even settable, so there is no "seed" to pin. Exact regeneration is
therefore impossible and saying otherwise in the write-up would be false.

What *is* reproducible is everything downstream of the responses, provided the
responses themselves are archived. So the cache is the reproducibility story:

- Every analysis re-run in January costs nothing and returns byte-identical
  inputs, because it reads from here rather than from the API.
- The whole pipeline can run with no network at all (``cache_only``), which is
  also how a reviewer could re-check the analysis without an API key.
- The cache directory plus its manifest is the archival artifact -- the thing
  that gets a DOI and makes "N calls, sha256 manifest" a checkable claim.

**The key hashes the rendered prompt, never the template plus its parameters.**
If the key were built from a template id and its substitutions, editing the
template's wording without changing its id would silently serve responses
generated by the *old* wording -- producing an analysis of prompts that were
never actually sent. Hashing the final string makes that failure impossible:
different text is a different key and simply misses.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from thesis.llm.base import CompletionRequest, CompletionResponse, Message, Usage

CACHE_FORMAT_VERSION = 1


class CacheMissError(RuntimeError):
    """Raised when a cache-only run needs a response it does not have."""


def _canonical_payload(request: CompletionRequest, provider: str) -> dict[str, Any]:
    """The exact set of fields that make two calls interchangeable.

    ``metadata`` is deliberately excluded: it carries run bookkeeping (grid
    cell ids, replicate numbers) that does not change what the model is asked
    and must not fragment the cache. Everything that *does* reach the provider
    is included, so a change to any of it correctly misses.
    """
    return {
        "v": CACHE_FORMAT_VERSION,
        "provider": provider,
        "model": request.model,
        "system": request.system,
        "messages": [{"role": m.role, "content": m.content} for m in request.messages],
        "max_tokens": request.max_tokens,
        "output_schema": request.output_schema,
        # Distinguishes independent draws of an identical prompt; see
        # CompletionRequest.variant. Excluding it would collapse every
        # replicate onto one cached response.
        "variant": request.variant,
    }


def cache_key(request: CompletionRequest, provider: str) -> str:
    """Stable sha256 over the canonical payload.

    ``sort_keys`` and a fixed separator matter more than they look: Python's
    dict ordering is insertion-ordered, so without sorting, two logically
    identical requests built by different code paths would hash differently
    and quietly double the API bill.
    """
    blob = json.dumps(
        _canonical_payload(request, provider),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


class ResponseCache:
    """A directory of JSON files, one per cached response.

    Entries are sharded by the first two characters of the key. A flat
    directory of ~13,000 files is slow to list on most filesystems and
    unpleasant to inspect by hand; 256 subdirectories keeps both manageable.
    """

    def __init__(self, root: Path, *, cache_only: bool = False) -> None:
        self.root = Path(root)
        self.cache_only = cache_only
        self._hits = 0
        self._misses = 0

    def _path(self, key: str) -> Path:
        return self.root / key[:2] / f"{key}.json"

    def __contains__(self, key: str) -> bool:
        return self._path(key).is_file()

    @property
    def hits(self) -> int:
        return self._hits

    @property
    def misses(self) -> int:
        return self._misses

    def get(self, key: str) -> CompletionResponse | None:
        """Return the cached response, or ``None`` on a miss.

        A hit is flagged with ``from_cache=True`` so downstream code and run
        manifests can tell a served response from a freshly paid one -- which
        is what makes "this run cost $0" a verifiable statement rather than an
        assertion.
        """
        path = self._path(key)
        if not path.is_file():
            self._misses += 1
            if self.cache_only:
                msg = f"cache-only run, but {key} is not cached"
                raise CacheMissError(msg)
            return None

        record = json.loads(path.read_text(encoding="utf-8"))
        response = record["response"]
        self._hits += 1
        return CompletionResponse(
            text=response["text"],
            usage=Usage(**response["usage"]),
            model=response["model"],
            stop_reason=response.get("stop_reason"),
            parsed=response.get("parsed"),
            request_id=response.get("request_id"),
            from_cache=True,
        )

    def put(
        self,
        key: str,
        request: CompletionRequest,
        response: CompletionResponse,
        provider: str,
    ) -> None:
        """Store a response.

        The full request is stored alongside it, not just the key. A bare hash
        is unauditable: with the request text on disk, the archive can be
        inspected, spot-checked, and quoted in the thesis without re-deriving
        anything, and a suspected key collision can actually be investigated.
        """
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        record = {
            "key": key,
            "cached_at": datetime.now(UTC).isoformat(timespec="seconds"),
            "request": _canonical_payload(request, provider),
            "response": {
                "text": response.text,
                "usage": asdict(response.usage),
                "model": response.model,
                "stop_reason": response.stop_reason,
                "parsed": response.parsed,
                "request_id": response.request_id,
            },
        }
        # Write to a temporary file and move it into place, so an interrupted
        # run can never leave a half-written entry that later parses as valid
        # JSON or crashes the next read.
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(record, indent=2, sort_keys=True), encoding="utf-8")
        tmp.replace(path)

    def entries(self) -> list[Path]:
        """Every cached entry, sorted -- the basis of the archive manifest."""
        return sorted(self.root.glob("*/*.json"))

    def manifest(self) -> dict[str, Any]:
        """A checkable description of the archive.

        Hashing each entry's bytes means the published archive can be verified
        as unmodified, which is the difference between "we archived the
        responses" and a claim a reader can confirm.
        """
        digests: dict[str, str] = {}
        for path in self.entries():
            digests[path.stem] = hashlib.sha256(path.read_bytes()).hexdigest()
        combined = hashlib.sha256(
            "".join(f"{k}{v}" for k, v in sorted(digests.items())).encode("utf-8")
        ).hexdigest()
        return {
            "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
            "format_version": CACHE_FORMAT_VERSION,
            "n_entries": len(digests),
            "combined_sha256": combined,
            "entries": digests,
        }


def build_messages(user: str, assistant: str | None = None) -> list[Message]:
    """Small helper for the common one- or two-turn shape."""
    messages = [Message(role="user", content=user)]
    if assistant is not None:
        messages.append(Message(role="assistant", content=assistant))
    return messages
