"""LLM-layer tests.

No live API calls. What is tested here is the logic the thesis's
reproducibility and cost claims rest on: that the cache key is stable and
discriminating, that a cached response round-trips exactly, and that the cost
model prices cached, batched, and fresh calls differently and correctly.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from thesis.llm.anthropic_client import UnknownModelError, capabilities_for
from thesis.llm.base import CompletionRequest, CompletionResponse, Message, Usage
from thesis.llm.cache import CacheMissError, ResponseCache, cache_key
from thesis.llm.cost import (
    BudgetExceededError,
    CostLedger,
    LedgerEntry,
    UnknownModelPriceError,
    cost_usd,
    guard_budget,
    project_cost_usd,
)


def _request(**overrides: object) -> CompletionRequest:
    base: dict[str, object] = {
        "model": "claude-opus-5",
        "messages": [Message(role="user", content="Reply to this email.")],
        "max_tokens": 1024,
        "system": "You are a persona.",
    }
    base.update(overrides)
    return CompletionRequest(**base)  # type: ignore[arg-type]


# --------------------------------------------------------------- cache keys


def test_cache_key_is_stable_across_identical_requests() -> None:
    assert cache_key(_request(), "anthropic") == cache_key(_request(), "anthropic")


def test_cache_key_changes_when_prompt_text_changes() -> None:
    """The central guarantee: different rendered text is a different key.

    This is what prevents a template edit from silently serving responses
    generated by the previous wording.
    """
    other = _request(messages=[Message(role="user", content="Reply to this email!")])
    assert cache_key(_request(), "anthropic") != cache_key(other, "anthropic")


def test_cache_key_changes_when_system_prompt_changes() -> None:
    other = _request(system="You are a different persona.")
    assert cache_key(_request(), "anthropic") != cache_key(other, "anthropic")


def test_cache_key_changes_across_models_and_providers() -> None:
    assert cache_key(_request(), "anthropic") != cache_key(
        _request(model="claude-sonnet-5"), "anthropic"
    )
    assert cache_key(_request(), "anthropic") != cache_key(_request(), "openai")


def test_cache_key_ignores_run_metadata() -> None:
    """Metadata is bookkeeping, not part of what the model was asked.

    If it fragmented the key, every replicate would miss the cache and the
    same prompt would be paid for repeatedly.
    """
    tagged = _request(metadata={"grid_cell": "p03_s12", "replicate": "4"})
    assert cache_key(_request(), "anthropic") == cache_key(tagged, "anthropic")


def test_cache_key_is_insensitive_to_field_construction_order() -> None:
    """Two equal requests built in different orders must hash identically."""
    a = CompletionRequest(
        model="claude-opus-5",
        messages=[Message(role="user", content="hi")],
        max_tokens=10,
        system="s",
    )
    b = CompletionRequest(
        system="s",
        max_tokens=10,
        messages=[Message(role="user", content="hi")],
        model="claude-opus-5",
    )
    assert cache_key(a, "anthropic") == cache_key(b, "anthropic")


# ------------------------------------------------------------ cache storage


def _response() -> CompletionResponse:
    return CompletionResponse(
        text='{"decision": "accept"}',
        usage=Usage(input_tokens=100, output_tokens=20, cache_read_input_tokens=400),
        model="claude-opus-5",
        stop_reason="end_turn",
        parsed={"decision": "accept"},
        request_id="req_abc",
    )


def test_cache_round_trip_preserves_response(tmp_path: Path) -> None:
    cache = ResponseCache(tmp_path)
    request, response = _request(), _response()
    key = cache_key(request, "anthropic")

    assert cache.get(key) is None
    cache.put(key, request, response, "anthropic")

    restored = cache.get(key)
    assert restored is not None
    assert restored.text == response.text
    assert restored.parsed == response.parsed
    assert restored.usage == response.usage
    assert restored.stop_reason == "end_turn"
    assert restored.from_cache is True


def test_cache_records_hits_and_misses(tmp_path: Path) -> None:
    cache = ResponseCache(tmp_path)
    key = cache_key(_request(), "anthropic")
    cache.get(key)
    cache.put(key, _request(), _response(), "anthropic")
    cache.get(key)
    assert (cache.hits, cache.misses) == (1, 1)


def test_cache_only_run_raises_on_miss(tmp_path: Path) -> None:
    """A cache-only run must fail loudly rather than silently skip work."""
    cache = ResponseCache(tmp_path, cache_only=True)
    with pytest.raises(CacheMissError):
        cache.get(cache_key(_request(), "anthropic"))


def test_manifest_covers_every_entry_and_changes_with_content(tmp_path: Path) -> None:
    cache = ResponseCache(tmp_path)
    cache.put(cache_key(_request(), "anthropic"), _request(), _response(), "anthropic")
    first = cache.manifest()
    assert first["n_entries"] == 1

    other = _request(messages=[Message(role="user", content="different")])
    cache.put(cache_key(other, "anthropic"), other, _response(), "anthropic")
    second = cache.manifest()

    assert second["n_entries"] == 2
    assert second["combined_sha256"] != first["combined_sha256"]


# -------------------------------------------------------------------- usage


def test_total_input_tokens_includes_cached_tokens() -> None:
    """input_tokens is the uncached remainder only -- the sum is the real size."""
    usage = Usage(input_tokens=10, cache_creation_input_tokens=100, cache_read_input_tokens=900)
    assert usage.total_input_tokens == 1010


def test_usage_sums() -> None:
    total = sum([Usage(input_tokens=1, output_tokens=2), Usage(input_tokens=3, output_tokens=4)])
    assert total == Usage(input_tokens=4, output_tokens=6)


# --------------------------------------------------------------------- cost


def test_cost_matches_hand_arithmetic() -> None:
    """1M input + 1M output on Opus 5 is $5 + $25."""
    usage = Usage(input_tokens=1_000_000, output_tokens=1_000_000)
    assert cost_usd("claude-opus-5", usage) == pytest.approx(30.0)


def test_batch_is_half_price() -> None:
    usage = Usage(input_tokens=1_000_000, output_tokens=1_000_000)
    full = cost_usd("claude-opus-5", usage)
    assert cost_usd("claude-opus-5", usage, batch=True) == pytest.approx(full / 2)


def test_cache_reads_are_far_cheaper_than_fresh_input() -> None:
    fresh = cost_usd("claude-opus-5", Usage(input_tokens=1_000_000))
    cached = cost_usd("claude-opus-5", Usage(cache_read_input_tokens=1_000_000))
    assert cached == pytest.approx(fresh * 0.10)


def test_cache_writes_cost_more_than_fresh_input() -> None:
    fresh = cost_usd("claude-opus-5", Usage(input_tokens=1_000_000))
    written = cost_usd("claude-opus-5", Usage(cache_creation_input_tokens=1_000_000))
    assert written == pytest.approx(fresh * 1.25)


def test_unknown_model_price_is_an_error_not_zero() -> None:
    with pytest.raises(UnknownModelPriceError):
        cost_usd("gpt-4o", Usage(input_tokens=10))


def test_budget_guard_trips_above_ceiling() -> None:
    projected = project_cost_usd(
        "claude-opus-5", n_calls=2000, input_tokens_each=2000, expected_output_tokens_each=500
    )
    guard_budget(projected, max_cost_usd=projected + 1)
    with pytest.raises(BudgetExceededError):
        guard_budget(projected, max_cost_usd=projected - 1)


# ------------------------------------------------------------------- ledger


def test_ledger_appends_and_totals(tmp_path: Path) -> None:
    ledger = CostLedger(tmp_path / "cost_ledger.csv")
    entry = LedgerEntry(
        run_id="run1",
        provider="anthropic",
        model="claude-opus-5",
        call_kind="simulate",
        usage=Usage(input_tokens=1_000_000, output_tokens=1_000_000),
    )
    ledger.record(entry)
    ledger.record(entry)
    assert ledger.total_usd() == pytest.approx(60.0)


def test_cached_calls_cost_nothing(tmp_path: Path) -> None:
    """A cache hit never reached the provider, so it must not be billed."""
    ledger = CostLedger(tmp_path / "cost_ledger.csv")
    ledger.record(
        LedgerEntry(
            run_id="run1",
            provider="anthropic",
            model="claude-opus-5",
            call_kind="simulate",
            usage=Usage(input_tokens=1_000_000, output_tokens=1_000_000),
            from_cache=True,
        )
    )
    assert ledger.total_usd() == pytest.approx(0.0)


# ------------------------------------------------------------- capabilities


def test_opus_5_rejects_sampling_params_and_caches_from_512_tokens() -> None:
    """These two facts are why the plan's temperature factor was dropped."""
    caps = capabilities_for("claude-opus-5")
    assert caps.supports_sampling_params is False
    assert caps.min_cacheable_prompt_tokens == 512
    assert caps.thinking_on_by_default is True


def test_sonnet_5_has_a_higher_cache_minimum_than_opus_5() -> None:
    """Assuming a uniform minimum would silently disable caching on Sonnet."""
    assert (
        capabilities_for("claude-sonnet-5").min_cacheable_prompt_tokens
        > capabilities_for("claude-opus-5").min_cacheable_prompt_tokens
    )


def test_unknown_model_capabilities_raise() -> None:
    with pytest.raises(UnknownModelError):
        capabilities_for("claude-opus-4-1")
