"""Can the judge see the failure a human reader sees?

Reading 100 generated replies against the messages they answer turns up one
dominant failure: the model answers a request by restating it back to the
person who made it. A quarter of the sample does this. The LLM judge, scoring
the same replies, reports them as equivalent to real ones.

Both cannot be right, and the reason they disagree is structural rather than a
matter of taste: :func:`thesis.judge.prompt.render_item_block` shows the judge
the reply and nothing else, while two of the six rubric dimensions ask about
fit to "the specific message it is responding to". A reply that mirrors its
stimulus is, read on its own, a perfectly well-formed email. The information
needed to catch it was never in the prompt.

This module measures that, rather than asserting it. The same replies are
scored twice -- once as the design has always scored them, once with the
incoming message included -- and both are compared against the manual codes.
The question is narrow and falsifiable: does ``contextual_fit`` separate the
mirrored replies from the sound ones, and does adding context change that?

**The judge model is not the simulator model.** Replies were generated by
llama3.2:3b, so scoring defaults to qwen2.5:3b -- the project's existing
free stand-in for "a different model family", the same pairing the judge-swap
pilot used.

Run with ``python -m thesis.analysis.judge_blindness``.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd
from scipy import stats

from thesis.analysis.plots import plot_factor_interaction
from thesis.judge.prompt import JudgeItem
from thesis.judge.run import JudgeResult, score_items
from thesis.llm.cache import ResponseCache
from thesis.llm.cost import CostLedger
from thesis.logging_setup import configure_logging, get_logger
from thesis.paths import (
    CACHE_DIR,
    COST_LEDGER,
    DOCS_FIGURES_DIR,
    MANIFESTS_DIR,
    TABLES_DIR,
    ensure_dirs,
)

log = get_logger(__name__)

DEFAULT_JUDGE_MODEL = "qwen2.5:3b"
CODED_PATH: Path = TABLES_DIR / "manual_review_coded_first_pass.csv"

# The dimension the argument is about: it is the one that explicitly asks
# about the message being replied to.
FOCUS_DIMENSION = "contextual_fit"


def build_items(frame: pd.DataFrame, *, with_context: bool) -> list[JudgeItem]:
    """One judge item per reviewed reply, with or without its incoming message."""
    return [
        JudgeItem(
            item_id=f"{'ctx' if with_context else 'noctx'}_{row.item}",
            text=str(row.generated_reply),
            is_generated=True,
            source_id=str(row.thread_id),
            context=str(row.stimulus_text) if with_context else None,
        )
        for row in frame.itertuples()
    ]


def scores_frame(results: Sequence[JudgeResult], frame: pd.DataFrame, *, arm: str) -> pd.DataFrame:
    """Judge scores joined back to the manual codes, one row per item."""
    by_position = {int(result.item_id.split("_")[-1]): result for result in results}
    rows = []
    for row in frame.itertuples():
        result = by_position.get(int(row.item))
        if result is None:
            continue
        rows.append(
            {
                "item": int(row.item),
                "arm": arm,
                "failure_mode": row.failure_mode,
                "mirrored": row.failure_mode == "mirrors_request",
                **{f"score_{key}": value for key, value in result.scores.items()},
            }
        )
    return pd.DataFrame.from_records(rows)


def summarize(scored: pd.DataFrame) -> dict[str, object]:
    """Mean scores by arm and by whether a human coded the reply as mirrored.

    Each arm's gap gets a rank-sum test, because the whole question is whether
    a difference of a third of a rubric point is a signal at all: the scores
    are 1-5 integers over 25 mirrored and 75 sound replies, and a mean
    difference that size can easily be nothing. Reporting the means without
    the test would let a null read as a finding.
    """
    summary: dict[str, object] = {}
    for arm, arm_frame in scored.groupby("arm"):
        column = f"score_{FOCUS_DIMENSION}"
        sound = arm_frame.loc[~arm_frame["mirrored"], column]
        mirrored = arm_frame.loc[arm_frame["mirrored"], column]
        statistic, p_value = stats.mannwhitneyu(sound, mirrored, alternative="two-sided")
        summary[str(arm)] = {
            "n": len(arm_frame),
            "n_mirrored": len(mirrored),
            "mean_contextual_fit_sound": round(float(sound.mean()), 2),
            "mean_contextual_fit_mirrored": round(float(mirrored.mean()), 2),
            "gap": round(float(sound.mean() - mirrored.mean()), 2),
            "mann_whitney_u": float(statistic),
            "p_value": round(float(p_value), 3),
            "mean_all_dimensions": {
                name.removeprefix("score_"): round(float(arm_frame[name].mean()), 2)
                for name in arm_frame.columns
                if name.startswith("score_")
            },
        }
    summary["context_effect"] = _context_effect(scored)
    return summary


def _context_effect(scored: pd.DataFrame) -> dict[str, object]:
    """How much every score moves when the judge is also shown the stimulus.

    Paired by item -- the same reply scored twice -- so this is a signed-rank
    test rather than a rank-sum one. It is a separate question from whether the
    judge can tell mirrored replies apart: a judge can become uniformly more
    generous without becoming any better at discriminating, and that turns out
    to be exactly what happens.
    """
    wide = scored.pivot(index="item", columns="arm")
    effects: dict[str, object] = {}
    for column in (c for c in scored.columns if c.startswith("score_")):
        with_context = wide[(column, "with context")]
        reply_only = wide[(column, "reply only")]
        _, p_value = stats.wilcoxon(with_context, reply_only)
        effects[column.removeprefix("score_")] = {
            "shift": round(float((with_context - reply_only).mean()), 2),
            "p_value": round(float(p_value), 4),
        }
    return effects


def plot(scored: pd.DataFrame) -> Path:
    """The interaction the result lives in: two lines, one per manual code."""
    means = scored.groupby(["arm", "mirrored"])[f"score_{FOCUS_DIMENSION}"].mean()
    arms = ("reply only", "with context")
    return plot_factor_interaction(
        arms,
        {
            "coded sound by a reader": tuple(float(means[(arm, False)]) for arm in arms),
            "coded as mirroring the request": tuple(float(means[(arm, True)]) for arm in arms),
        },
        path=DOCS_FIGURES_DIR / "judge_context_contextual_fit.png",
        title="Showing the judge the incoming message: more generous, no better",
        subtitle=(
            "Both lines rise (p<.001); neither gap between them is distinguishable from "
            "noise (p=.32, p=.38). n=100, scored twice."
        ),
        x_label="what the judge was shown",
        y_label="mean contextual-fit score (1-5)",
        legend_loc="upper left",
    )


def run(
    frame: pd.DataFrame, client: object, *, model: str, variant: str = "neutral"
) -> tuple[pd.DataFrame, dict[str, object]]:
    """Score every reviewed reply in both arms and return the joined scores."""
    cache = ResponseCache(CACHE_DIR)
    ledger = CostLedger(COST_LEDGER)
    run_id = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")

    frames = []
    for arm, with_context in (("reply only", False), ("with context", True)):
        results, summary = score_items(
            build_items(frame, with_context=with_context),
            client,  # type: ignore[arg-type]
            variant=variant,  # type: ignore[arg-type]
            model=model,
            cache=cache,
            ledger=ledger,
            run_id=run_id,
        )
        log.info(
            "%s: %d scored, %d from cache, %d invalid",
            arm,
            summary.n_scored,
            summary.n_from_cache,
            summary.n_invalid,
        )
        frames.append(scores_frame(results, frame, arm=arm))

    scored = pd.concat(frames, ignore_index=True)
    return scored, summarize(scored)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coded", default=str(CODED_PATH))
    parser.add_argument("--model", default=DEFAULT_JUDGE_MODEL)
    parser.add_argument("--out", default=str(TABLES_DIR / "judge_context_scores.csv"))
    args = parser.parse_args()

    configure_logging()
    ensure_dirs()

    from thesis.llm.ollama_client import OllamaClient, OllamaUnavailableError

    client = OllamaClient(args.model)
    if not client.is_available():
        msg = "no Ollama server reachable; start it with 'ollama serve'."
        raise OllamaUnavailableError(msg)

    frame = pd.read_csv(args.coded)
    scored, summary = run(frame, client, model=args.model)
    scored.to_csv(args.out, index=False)
    log.info("wrote %s", plot(scored))
    (MANIFESTS_DIR / "judge_blindness.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8"
    )
    log.info("judge blindness summary: %s", json.dumps(summary))


if __name__ == "__main__":
    main()
