"""Generate each persona's memory store -- the one piece of the memory stream
that was never actually built.

``memory.py`` has always had working, tested retrieval (recency, importance,
relevance, reflection batching). What it never had was anything to retrieve
*from*: every reply generated by this project so far, in every demo, ran with
an empty memory store, because nothing populated one. This module is that
missing piece.

**Two LLM calls per persona, not per (persona x counterpart_rank).** The
original plan estimated ~100 calls across 50 persona/counterpart-rank pairs.
The architecture actually built retrieves from *one* store per persona and
lets the retrieval query (built from persona + direction) do the work of
surfacing different memories for different directions -- see
``prompt.retrieve_for_group``. So generation only needs to happen once per
persona: one call for observations, a handful more for reflections batched
over them. Ten personas, roughly four calls each, well under the original
budget -- smaller because the design is, not because anything was skipped.

**Synthetic timestamps, not generated ones.** Observations are spread across a
fixed recent window (:data:`OBSERVATION_WINDOW_HOURS`) in generation order
rather than asking the model for a timestamp -- small models are considerably
better at writing a plausible sentence than at producing well-calibrated
relative time deltas, and the recency signal only needs *an* ordering, not the
model's opinion of one.

**Importance is an ordinal enum, not a free number**, for the same reason
``schemas.py`` made ``confidence`` one: structured-output APIs do not reliably
enforce numeric bounds, so a 1-10 field could not actually be constrained to
1-10. Three levels, mapped to fixed floats.

**The same re-identification guard as personas.** The generation prompt
explicitly asks for no real names, no real companies, nothing tied to an
actual news event -- for the same reason the personas themselves are
archetypes rather than named individuals: an invented memory that happens to
recall a real fact is memorization wearing a costume.

**This is a free-mode artifact, with a real caveat to state plainly.** The
committed snapshot (:data:`MEMORY_SNAPSHOT_PATH`) is generated with the local
Ollama model, for the same reason the persona snapshot exists: so the demos
work for anyone without requiring a paid call. But the actual thesis run
should regenerate memory with the *same* model family used for simulation,
not a smaller local one -- mixing a weak model's invented memories into a
frontier model's generation is a real confound, not a stylistic nicety, and
should not be waved through unexamined once real credentials exist.

Run with ``python -m thesis.sim.memory_generation``.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from dataclasses import asdict
from typing import Any, Final, Protocol

from thesis.llm.base import CompletionRequest, CompletionResponse, LLMClient, Message
from thesis.logging_setup import configure_logging, get_logger
from thesis.paths import EXTERNAL_DIR
from thesis.sim.memory import (
    REFLECTIONS_PER_TRIGGER,
    MemoryItem,
    as_reflection,
    build_reflection_prompt,
    reflection_batches,
)
from thesis.sim.persona import Persona

log = get_logger(__name__)


class _CompletionClient(Protocol):
    """The one capability generation actually needs.

    Narrower than LLMClient for the same reason batch.py has BatchClient:
    stating the real dependency rather than the whole client protocol means a
    test double only has to implement what is actually called, and the type
    system correctly admits any client capable of a single completion.
    """

    def complete(self, request: CompletionRequest) -> CompletionResponse: ...


MEMORY_SNAPSHOT_PATH = EXTERNAL_DIR / "memory_snapshot.json"

OBSERVATIONS_PER_PERSONA = 15
# Spread across roughly three simulated weeks -- long enough for the
# recency signal to actually discriminate between items, short enough to
# still read as "recent" in the observation prompt's own framing.
OBSERVATION_WINDOW_HOURS = 500.0

IMPORTANCE_LEVELS: Final[tuple[str, ...]] = ("low", "medium", "high")
IMPORTANCE_VALUE: Final[dict[str, float]] = {"low": 0.2, "medium": 0.5, "high": 0.9}
# Reflections are, by construction, the salient generalizations a person
# actually carries forward -- not one more equally-weighted data point --
# so they are seeded at a fixed high importance rather than asked of the
# model a second time.
REFLECTION_IMPORTANCE = 0.9

OBSERVATION_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {
        "observations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "One short, concrete thing that happened.",
                    },
                    "importance": {"type": "string", "enum": list(IMPORTANCE_LEVELS)},
                },
                "required": ["text", "importance"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["observations"],
    "additionalProperties": False,
}

REFLECTION_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {"reflections": {"type": "array", "items": {"type": "string"}}},
    "required": ["reflections"],
    "additionalProperties": False,
}


def build_observation_prompt(persona: Persona, n: int) -> str:
    """The prompt asking a model to invent a persona's recent history.

    Deliberately separate from ``render_persona_block`` -- that prompt is
    about *how to write an email*; this one is about *what happened*, and
    reusing the email-writing framing here would be a category mismatch.
    """
    return (
        f"You are a {persona.rank_label} in the {persona.department} function "
        "of a large US energy company in 2001.\n\n"
        f"List {n} short, plausible things that might have happened in your "
        "working life over the past few weeks -- the kind of small, concrete "
        "events someone at this level would actually have on their mind: a "
        "deal that needed sign-off, a number that didn't reconcile, a meeting "
        "that ran long, a report that came in late. State each as something "
        "that happened, in one short sentence -- not as advice, and not as a "
        "general habit.\n\n"
        "Do not invent the names of real people or real companies, and do not "
        "reference any specific real news event -- keep everything generic to "
        "the role.\n\n"
        "For each one, also rate how significant it would feel to someone in "
        "this role: low, medium, or high."
    )


def generate_observations(
    persona: Persona, client: _CompletionClient, *, n: int = OBSERVATIONS_PER_PERSONA
) -> list[MemoryItem]:
    """One call: invent ``n`` observations, spread across a synthetic recent window."""
    request = CompletionRequest(
        model=getattr(client, "model", getattr(client, "model_label", "unknown")),
        messages=[Message(role="user", content=build_observation_prompt(persona, n))],
        max_tokens=1024,
        output_schema=OBSERVATION_SCHEMA,
    )
    response = client.complete(request)
    raw = (response.parsed or {}).get("observations", [])[:n]

    items = []
    denom = max(len(raw) - 1, 1)
    for i, entry in enumerate(raw):
        text = str(entry.get("text", "")).strip()
        if not text:
            continue
        # Earliest-generated item is treated as the oldest; spread linearly
        # down to "just now" for the most recent -- see the window comment
        # above for why this is assigned rather than asked of the model.
        hours_ago = OBSERVATION_WINDOW_HOURS * (1 - i / denom)
        importance = IMPORTANCE_VALUE.get(str(entry.get("importance", "medium")), 0.5)
        items.append(MemoryItem(text=text, importance=importance, hours_ago=hours_ago))
    return items


def generate_reflections(
    observations: Sequence[MemoryItem], client: _CompletionClient
) -> list[MemoryItem]:
    """A handful of calls: one per batch of observations, per reflection_batches()."""
    reflections: list[MemoryItem] = []
    for batch in reflection_batches(observations):
        request = CompletionRequest(
            model=getattr(client, "model", getattr(client, "model_label", "unknown")),
            messages=[
                Message(
                    role="user",
                    content=build_reflection_prompt(batch, REFLECTIONS_PER_TRIGGER),
                )
            ],
            max_tokens=512,
            output_schema=REFLECTION_SCHEMA,
        )
        response = client.complete(request)
        texts = (response.parsed or {}).get("reflections", [])[:REFLECTIONS_PER_TRIGGER]

        # Inherits the most recent observation's hours_ago in the batch, so a
        # reflection over old material does not present as a fresh memory.
        newest_hours_ago = min(item.hours_ago for item in batch)
        for text in texts:
            text = str(text).strip()
            if not text:
                continue
            base = MemoryItem(
                text=text, importance=REFLECTION_IMPORTANCE, hours_ago=newest_hours_ago
            )
            reflections.append(as_reflection(base))
    return reflections


def generate_persona_memory(
    persona: Persona, client: _CompletionClient, *, n_observations: int = OBSERVATIONS_PER_PERSONA
) -> list[MemoryItem]:
    """A persona's full store: its observations, plus reflections over them."""
    observations = generate_observations(persona, client, n=n_observations)
    reflections = generate_reflections(observations, client)
    return observations + reflections


def generate_all(
    personas: Sequence[Persona], client: _CompletionClient
) -> dict[str, list[MemoryItem]]:
    """One store per persona, keyed by persona_id."""
    stores = {}
    for persona in personas:
        stores[persona.persona_id] = generate_persona_memory(persona, client)
        log.info(
            "generated %d memory item(s) for %s",
            len(stores[persona.persona_id]),
            persona.persona_id,
        )
    return stores


def freeze_memory(stores: dict[str, list[MemoryItem]], path: Any = MEMORY_SNAPSHOT_PATH) -> None:
    """Write every persona's store to disk, mirroring persona.freeze_personas()."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {persona_id: [asdict(item) for item in items] for persona_id, items in stores.items()}
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def load_frozen_memory(path: Any = MEMORY_SNAPSHOT_PATH) -> dict[str, list[MemoryItem]]:
    """Load a previously generated snapshot rather than calling a model again."""
    if not path.is_file():
        msg = (
            f"no memory snapshot at {path}. Either generate one with "
            "python -m thesis.sim.memory_generation, or fetch the committed "
            "snapshot from the repository."
        )
        raise FileNotFoundError(msg)
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {persona_id: [MemoryItem(**item) for item in items] for persona_id, items in raw.items()}


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--local",
        metavar="MODEL",
        default="llama3.2:3b",
        help="Generate with a local Ollama model (default: llama3.2:3b).",
    )
    parser.add_argument(
        "--offline", action="store_true", help="Use the stub client instead (for smoke tests)."
    )
    args = parser.parse_args()

    configure_logging()

    client: LLMClient
    if args.offline:
        from thesis.llm.stub_client import StubClient

        client = StubClient()
    else:
        from thesis.llm.ollama_client import OllamaClient, OllamaUnavailableError

        client = OllamaClient(args.local)
        if not client.is_available():
            msg = (
                "no Ollama server reachable. Start it with 'ollama serve', "
                f"and pull the model with 'ollama pull {args.local}'."
            )
            raise OllamaUnavailableError(msg)

    from thesis.data.identity import resolve_owners
    from thesis.data.roles import build_role_index, load_employees, load_title_rank_table
    from thesis.paths import MESSAGES_PARQUET_GLOB
    from thesis.sim.persona import derive_personas

    title_ranks = load_title_rank_table()
    role_index, _ = build_role_index(
        load_employees(), resolve_owners(MESSAGES_PARQUET_GLOB), title_ranks
    )
    personas = derive_personas(
        {a: (r.seniority_rank, r.department) for a, r in role_index.items()},
        {rank: label for _, (rank, label) in title_ranks.items()},
    )

    stores = generate_all(personas, client)
    freeze_memory(stores)
    log.info("wrote memory for %d persona(s) to %s", len(stores), MEMORY_SNAPSHOT_PATH)


if __name__ == "__main__":
    main()
